services:
  - type: web
    name: media-sequencer-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_kz3qb1KTDdCp@ep-gentle-cake-b44uj6he-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
